print("Welcome to the Mad Libs Generator!")
holiday = input("Choose a holiday: ")
name = input("Choose a person's name: ")
verb = input("Choose a verb: ")
name1 = input("Choose a Store name: ")
noun = input("Choose a noun: ")
adj = input("Choose an adjective: ")
noun1 = input("Choose another noun: ")
adj1 = input("Choose an adjective: ")
noun2 = input("Choose another noun: ")
adj2 = input("Choose another adjective: ")
noun3 = input("Choose another noun: ")
name2 = input("Choose another person's name: ")
verb1 = input("Choose another verb: ")
verb2 = input("Choose another verb: ")
adj3 = input("Choose another adjective: ")
name3 = input("Choose another Store name: ")

mad_lib = f"It was almost {holiday}, so {name} knew they had to get grocery shopping. They {verb} to the {name1} and picked up a {noun}. They looked at their list. They needed to get {adj} {noun1}, {adj1} {noun2}, and {adj2} {noun3}. They couldn't find anything! Eventually they saw their friend, {name2}, and {verb1} them for help. Their friend {verb2}. \"You're in the {adj3} place!\"they said. \"This is a {name3}\""
print (mad_lib)