old = ('Old MacDonald had a farm, eieio. An on that farm he had a ')
eieio = (', eieio.')
animal = ('chicken')
print(old + animal + eieio)
animal = ('pig')
print(old + animal + eieio)
animal = ('cow')
print(old + animal + eieio)
animal = ('goat')
print(old + animal + eieio)