import os

def coder_agent(app_instance, project_path, prompt, api_url, model, api_provider="huggingface", token=None):
    """Generate code based on prompt with provider support"""
    from core.llm import call_llm
    from core.base_agent import BaseAgent

    # Create a dummy BaseAgent to use its requires_approval method
    # This is a temporary workaround until coder_agent is refactored into a class
    class DummyCoderAgent(BaseAgent):
        def __init__(self, app_instance):
            self.app = app_instance
            self.orchestrator = app_instance.agent_manager.orchestrator if hasattr(app_instance, 'agent_manager') else None

    dummy_agent = DummyCoderAgent(app_instance)
    
    # Get existing files for context
    context = ""
    try:
        for root, dirs, files in os.walk(project_path):
            for file in files:
                if file.endswith('.py'):
                    filepath = os.path.join(root, file)
                    rel_path = os.path.relpath(filepath, project_path)
                    with open(filepath, 'r', encoding='utf-8') as f:
                        content = f.read()[:1000]
                    context += f"\n--- {rel_path} ---\n{content}\n"
    except:
        pass
    
    system_prompt = f"""You are an expert Python developer. Generate code based on these requirements:

Requirements: {prompt}

Existing code in project:
{context}

Generate appropriate Python code. If main.py doesn't exist, create it.
Return a JSON object with keys:
- "files_created": list of filenames created
- "code": dictionary with filename as key and code content as value"""

    response = call_llm(system_prompt, api_url, model, api_provider, token)
    
    files_created = []
    
    # Try to parse JSON response
    try:
        import json
        start = response.find('{')
        end = response.rfind('}') + 1
        if start >= 0 and end > start:
            json_str = response[start:end]
            result = json.loads(json_str)
            
            if "code" in result:
                for filename, content in result["code"].items():
                    full_path = os.path.join(project_path, filename)
                    os.makedirs(os.path.dirname(full_path), exist_ok=True)
                    
                    if dummy_agent.requires_approval():
                        app_instance.log_ai(f"💡 I suggest creating/modifying {filename} with the following content:\n\n```python\n{content}\n```\n(Auto-Agent is disabled, please apply manually or enable Auto-Agent.)")
                        files_created.append(f"Proposed: {filename}")
                    else:
                        with open(full_path, 'w', encoding='utf-8') as f:
                            f.write(content)
                        files_created.append(filename)
                
                return files_created
    except:
        pass
    
    # Fallback: Create main.py if it doesn't exist
    main_path = os.path.join(project_path, "main.py")
    initial_main_content = f'''#!/usr/bin/env python3
"""
{os.path.basename(project_path)} - Generated by AI Dev IDE
"""

def main():
    """Main entry point"""
    print("Hello from AI Dev IDE!")
    print("Project prompt: {prompt}")
    
if __name__ == "__main__":
    main()
'''
    if not os.path.exists(main_path):
        if dummy_agent.requires_approval():
            app_instance.log_ai(f"💡 I suggest creating main.py with the following content:\n\n```python\n{initial_main_content}\n```\n(Auto-Agent is disabled, please apply manually or enable Auto-Agent.)")
            files_created.append("Proposed: main.py")
        else:
            with open(main_path, "w") as f:
                f.write(initial_main_content)
            files_created.append("main.py")
    
    return files_created